title: Joel Harp Portfolio
logo: "/images/Vegas.png?raw=true" # your photo (or logo) here

description:  # your text below (remove <br> elements if you don't need line breaks)
  
Business Operations Senior Associate
Branded Asset Management
Walt Disney World

  <br><br>
  
  
  
  
  
  
  <a href="https://www.linkedin.com/in/joelharp32/">View My LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal
