title: Joel Harp Portfolio
logo: "/images/Vegas.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Hello I am Joey Harp. I am part of the Branded Asset Team here at. I help to take
  care to preserve the magic by saving important assets from all of our parks and resorts, 
  from our ride vehicles and props to unique hotel room furniture and costumes.
  <br><br>
   I am involved with updating and maintaining the asset database. I am hoping to start 
   implementing some spatial data analysis to better track our assets from which ones 
   and from where they came from in the near future.
  <br><br>
  
  <a href="https://www.linkedin.com/in/joelharp32/">View My LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal
